// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelMinion.Infrastructure.Persistence;

#nullable disable

namespace TravelMinion.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TravelMinionDbContext))]
    [Migration("20261001021746_CountryBaseGeography")]
    partial class CountryBaseGeography
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelMinion.Domain.ResearchJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Progress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("ResearchJobs", (string)null);
                });

            modelBuilder.Entity("TravelMinion.Domain.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Activities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Itinerary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Trips", (string)null);
                });

            modelBuilder.Entity("TravelMinion.Domain.ResearchJob", b =>
                {
                    b.HasOne("TravelMinion.Domain.Trip", null)
                        .WithMany("ResearchJobs")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelMinion.Domain.Trip", b =>
                {
                    b.OwnsMany("TravelMinion.Domain.Suggestion", "Suggestions", b1 =>
                        {
                            b1.Property<Guid>("TripId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("ApproximateCost")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Area")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)");

                            b1.Property<string>("Confidence")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("CouldntVerify")
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)");

                            b1.Property<string>("Destination")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<bool>("Discarded")
                                .HasColumnType("bit");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)");

                            b1.Property<string>("OpeningHours")
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)");

                            b1.Property<string>("Rationale")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.Property<string>("SeasonWeatherFit")
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)");

                            b1.Property<string>("SourceLink")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.Property<string>("SourceName")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("TypicalDuration")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("TripId", "Id");

                            b1.ToTable("Suggestions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.OwnsOne("TravelMinion.Domain.TripBrief", "Brief", b1 =>
                        {
                            b1.Property<Guid>("TripId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Budget")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.PrimitiveCollection<string>("Dietary")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("GroupSize")
                                .HasColumnType("int");

                            b1.PrimitiveCollection<string>("Interests")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Mobility")
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)");

                            b1.PrimitiveCollection<string>("PreferredSources")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TravelStyle")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.PrimitiveCollection<string>("TravellersToShare")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TripId");

                            b1.ToTable("TripBriefs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TripId");

                            b1.OwnsOne("TravelMinion.Domain.Arrival", "Arrival", b2 =>
                                {
                                    b2.Property<Guid>("TripBriefTripId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("BaseName")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)");

                                    b2.Property<DateOnly>("Date")
                                        .HasColumnType("date");

                                    b2.Property<TimeOnly>("Time")
                                        .HasColumnType("time");

                                    b2.HasKey("TripBriefTripId");

                                    b2.ToTable("TripBriefs");

                                    b2.WithOwner()
                                        .HasForeignKey("TripBriefTripId");
                                });

                            b1.OwnsMany("TravelMinion.Domain.Country", "Countries", b2 =>
                                {
                                    b2.Property<Guid>("TripBriefTripId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)");

                                    b2.Property<int>("SpanInDays")
                                        .HasColumnType("int");

                                    b2.HasKey("TripBriefTripId", "Id");

                                    b2.ToTable("Countries", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("TripBriefTripId");

                                    b2.OwnsMany("TravelMinion.Domain.Base", "Bases", b3 =>
                                        {
                                            b3.Property<Guid>("CountryTripBriefTripId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<int>("CountryId")
                                                .HasColumnType("int");

                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("int");

                                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b3.Property<int>("Id"));

                                            b3.Property<int>("Days")
                                                .HasColumnType("int");

                                            b3.Property<string>("Name")
                                                .IsRequired()
                                                .HasMaxLength(200)
                                                .HasColumnType("nvarchar(200)");

                                            b3.Property<string>("TransitFromPrevious")
                                                .HasMaxLength(200)
                                                .HasColumnType("nvarchar(200)");

                                            b3.HasKey("CountryTripBriefTripId", "CountryId", "Id");

                                            b3.ToTable("Bases", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("CountryTripBriefTripId", "CountryId");
                                        });

                                    b2.Navigation("Bases");
                                });

                            b1.OwnsOne("TravelMinion.Domain.Departure", "Departure", b2 =>
                                {
                                    b2.Property<Guid>("TripBriefTripId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("BaseName")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)");

                                    b2.Property<DateOnly>("Date")
                                        .HasColumnType("date");

                                    b2.Property<TimeOnly>("Time")
                                        .HasColumnType("time");

                                    b2.HasKey("TripBriefTripId");

                                    b2.ToTable("TripBriefs");

                                    b2.WithOwner()
                                        .HasForeignKey("TripBriefTripId");
                                });

                            b1.Navigation("Arrival")
                                .IsRequired();

                            b1.Navigation("Countries");

                            b1.Navigation("Departure")
                                .IsRequired();
                        });

                    b.Navigation("Brief");

                    b.Navigation("Suggestions");
                });

            modelBuilder.Entity("TravelMinion.Domain.Trip", b =>
                {
                    b.Navigation("ResearchJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
